// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koapryvdrgflimeheezh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvYXByeXZkcmdmbGltZWhlZXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzE5NzIsImV4cCI6MjA3MTYwNzk3Mn0.g-DhQL7EGTtdT4IGMxPucO4ivvy7KMtgzkvUJhcdleU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});